INSERT INTO `unit` (`unitid`, `unit`, `abbreviation`, `parentunit`) VALUES 
(1,'Office of the Chief of Air Staff','Office of the CAS',NULL),
(2,'Policy & Plans Branch','Pol & Plans Branch',1),
(3,'Training & Operations Branch','Trg & Ops Branch',1),
(4,'Aircraft Engineering Branch','AcE Branch',1),
(5,'Logistics & Communications Branch','Log & Comms Branch',1),
(6,'Administration Branch','Admin Branch',1),
(7,'Standard Evaluation Branch','Stan Eval Branch',1),
(8,'Medical Services Branch','Medical Svcs Branch',1),
(9,'Air Secretary Branch','Air Sec Branch',1),
(10,'Accounts and Budget Branch','A & B Branch',1),
(11,'SI List','SI List',1),
(12,'AIRFORCE INSTITUTE OF TECHNOLOGY','AFIT',1),
(13,'Communication Branch','CComms Branch',1),
(14,'Chief of Communications ','CComms',1),
(15,'Chief of Logistics','CLog',1),
(18,'Logistic Branch','Log Branch',1);

INSERT INTO `appointment` (`appointmentid`, `appointment`, `abbreviation`, `parentappointment`, `unit`) 
VALUES (1,'Chief of the Air Staff','CAS',NULL,1),
(2,'Chief of Policy & Plans','COPP',1,2),
(3,'Chief of Training & Operations','CTOP',1,3),
(4,'Chief of Aircraft Engineering','CAcE',1,4),
(5,'Chief of Logistics & Communications','CLog & Comms',1,5),
(6,'Chief of Administration','COA',1,6),
(7,'Chief of Standard Evaluation','COSE',1,7),
(8,'Chief of Medical Services','CMS',1,8),
(9,'Air Secretary','Air Sec',1,9),
(10,'Chief of Accounts and Budget','CAB',1,10),
(11,'Principal Air Staff Officer to the Chief of Air Staff','PASO - CAS',1,1),
(12,'Air Assistant to the Chief of Air Staff','AA - CAS',1,1),
(13,'Director of Procurement','DPROC',5,5),
(14,'AFIT COMMANDANT','AFIT COMDT',1,12),
(15,'Chief of Communications','CComms',1,13),
(16,'Chief of Logistics','CLog',1,1);
